USE MirageDB;
GO

-- 1. Create a 'Technician' role if it doesn't exist
IF NOT EXISTS (SELECT 1 FROM Roles WHERE RoleName = 'Technician')
BEGIN
    INSERT INTO Roles (RoleName) VALUES ('Technician');
END
GO

-- 2. Create a new user named 'normaluser'
--    This user's ID will be 2 (since testuser is 1)
IF NOT EXISTS (SELECT 1 FROM Users WHERE Username = 'normaluser')
BEGIN
    -- NOTE: We are storing a HASH of the password 'Password456!', not the password itself.
    -- This hash is generated by BCrypt.
    INSERT INTO Users (Username, PasswordHash, FullName, IsActive)
    VALUES ('normaluser', '$2a$11$G.7O/V82OD.K.EUyv68.Fe.J42d8aC1xS02/avL8ohG/E5vERk22e', 'Normal User', 1);
END
GO

-- 3. Assign the 'Technician' role to the new user
DECLARE @technicianRoleId INT = (SELECT RoleID FROM Roles WHERE RoleName = 'Technician');
DECLARE @normalUserId INT = (SELECT UserID FROM Users WHERE Username = 'normaluser');

IF NOT EXISTS (SELECT 1 FROM UserRoles WHERE UserID = @normalUserId AND RoleID = @technicianRoleId)
BEGIN
    INSERT INTO UserRoles (UserID, RoleID) VALUES (@normalUserId, @technicianRoleId);
END
GO